name: Build Harbor Aarch64
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-branches:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04-arm
    env:
      Harbor_Git_Tag: 'v2.15.2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt autoremove -y

      - name: Install dependencies & Docker
        run: |
          sudo apt update
          sudo apt install -y make git curl jq unzip build-essential ca-certificates
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Build & Package Harbor (v2.15.2 test build)
        run: |
          bash build-harbor-aarch64.sh
          docker images
          mkdir -p all-in-one/harbor
          curl -L https://raw.githubusercontent.com/goharbor/harbor/${Harbor_Git_Tag}/LICENSE -o all-in-one/harbor/LICENSE
          curl -L https://raw.githubusercontent.com/goharbor/harbor/${Harbor_Git_Tag}/make/common.sh -o all-in-one/harbor/common.sh
          curl -L https://raw.githubusercontent.com/goharbor/harbor/${Harbor_Git_Tag}/make/harbor.yml.tmpl -o all-in-one/harbor/harbor.yml.tmpl
          curl -L https://raw.githubusercontent.com/goharbor/harbor/${Harbor_Git_Tag}/make/install.sh -o all-in-one/harbor/install.sh
          curl -L https://raw.githubusercontent.com/goharbor/harbor/${Harbor_Git_Tag}/make/prepare -o all-in-one/harbor/prepare
          sed -i "s#goharbor/prepare:dev#goharbor/prepare:${Harbor_Git_Tag}-aarch64#g" all-in-one/harbor/prepare
          docker save $(docker images | grep "goharbor" | grep "-aarch64" | awk '{print $1":"$2}') | gzip > all-in-one/harbor/harbor.${Harbor_Git_Tag}.tar.gz

      # 仅上传到 workflow 制品，不会创建 Release，构建完手动下载
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: harbor-offline-aarch64-v2.15.2
          path: all-in-one/harbor/harbor.${{ env.Harbor_Git_Tag }}.tar.gz
